name: Publish

on:
  push:
    tags:
      - v*.*.*




jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: /home/runner/.cache/pypoetry/virtualenvs
          installer-parallel: true
      - name: Publsh package
        env:
            PYPI_USERNAME:  ${{ secrets.PYPI_USERNAME }}
            PYPI_PASSWORD : ${{ secrets.PYPI_PASSWORD }}
        run:
          poetry publish  --username $PYPI_USERNAME --password  $PYPI_PASSWORD --build
